name: EDK2

on: [push, pull_request]

env:
  BUILD_TYPE: RELEASE
  COMPILER: GCC5
  TARGET_TYPE: x64
  TARGET_ARCH: X64

jobs:
  Linux-EDK2-Build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Linux environment
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install python3-distutils nasm uuid-dev gcc-multilib

    - name: Set up EDK2
      run: |
        git clone --recursive https://github.com/tianocore/edk2.git
        make -C edk2/BaseTools

    - name: Build UEFI bootloader
      run: |
        export WORKSPACE=$PWD
        export PACKAGES_PATH=$WORKSPACE:$WORKSPACE/edk2
        source edk2/edksetup.sh
        build -a ${{ env.TARGET_ARCH }} -b ${{ env.BUILD_TYPE }} -t ${{ env.COMPILER }} -p AmiNtfsBugPkg.dsc
        mv Build/${{ env.BUILD_TYPE }}_${{ env.COMPILER }}/${{ env.TARGET_ARCH }}/AmiNtfsBug.efi .

    - name: Display SHA-256
      run: sha256sum *.efi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.TARGET_TYPE }}
        path: ./*.efi
